language: node_js
node_js:
  - "7.0"
services:
  - postgresql
before_script:
  - psql -c 'create database car_crm_test;' -U postgres
install:
  - npm install -g knex
  - npm install
script:
  - knex migrate:latest --env test
  - knex seed:run --env test
  - npm test
